=== mojaloop/documentation/mojaloop-technical-overview/notifications/assets/schemas/eventNotifyReport.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "http://mojaloop.io/events/notifications/NotifyReport",
  "type": "object",
  "title": "NotifyReport",
  "description": "The root schema comprises the entire JSON document.",
  "default": {},
  "examples": [
      {
          "msgId": "18efb9ea-d29a-42b9-9b30-59e1e7cfe216",
          "msgKey": "861b86e6-c3da-48b3-ba17-896710287d1f",
          "msgName": "NotifyDelivered",
          "msgType": "Domain",
          "msgTopic": "NotificationEvents",
          "msgPartition": null,
          "msgTimestamp": 2007677081820,
          "aggregateName": "Notifications",
          "aggregateId": "861b86e6-c3da-48b3-ba17-896710287d1f",
          "notifyId": "3920382d-f78c-4023-adf9-0d7a4a2a3a2f",
          "report": {
              "requestTimestamp": 1507677081120,
              "deliveryTimestamp": 1607677081840,
              "deliveryReqLatency": 100,
              "retryAttempts": 1,
              "response": {
                  "statusCode": "202",
                  "statusDescription": "Accepted",
                  "headers": {
                      "content-type": "application/vnd.interoperability.transfers+json;version=1.0",
                      "date": "2019-05-28T16:34:41.000Z"
                  },
                  "body": "{}"
              },
              "accepted": true,
              "errorInformation": {
                  "errorCode": "408",
                  "errorDescription": "ECONNABORTED\ntimeout of 2ms exceeded\nError: timeout of 2ms exceeded\n    at createError (/node_modules/axios/lib/core/createError.js:16:15)\n    at Timeout.handleRequestTimeout (/node_modules/axios/lib/adapters/http.js:252:16)\n    at listOnTimeout (timers.js:324:15)\n    at processTimers (timers.js:268:5)"
              }
          },
          "traceInfo": {
              "traceParent": "00-8e540e87060d56a2d2e0be5d732791e7-d96a5971b7c5cac6-21",
              "traceState": "acmevendor=eyJzcGFuSWQiOiJkOTZhNTk3MWI3YzVjYWM2IiwidGltZUFwaVByZXBhcmUiOiIxNjA3Njc3MDgxNzAwIiwidGltZUFwaUZ1bGZpbCI6IjE2MDc2NzcwODE4MTkifQ==",
              "service": "notification-Cmd-handler",
              "startTimestamp": 1607677081837,
              "finishTimestamp": 2007677081838
          }
      }
  ],
  "required": [
      "msgId",
      "msgKey",
      "msgName",
      "msgType",
      "msgTopic",
      "msgPartition",
      "msgTimestamp",
      "aggregateName",
      "aggregateId",
      "notifyId",
      "report",
      "traceInfo"
  ],
  "properties": {
    "msgId": {
      "$id": "#/properties/msgId",
      "type": "string",
      "title": "The msgId schema",
      "description": "Unique identifier for this message. Generated by the NotificationEvtHandler.",
      "default": "",
      "examples": [
          "18efb9ea-d29a-42b9-9b30-59e1e7cfe216"
      ]
    },
    "msgKey": {
        "$id": "#/properties/msgKey",
        "type": "string",
        "title": "The msgKey schema",
        "description": "Mapped from the aggregateId, used by Kafka for Key-partitioning.",
        "default": "",
        "examples": [
            "861b86e6-c3da-48b3-ba17-896710287d1f"
        ]
    },
    "msgName": {
        "$id": "#/properties/msgName",
        "type": "string",
        "title": "The msgName schema",
        "description": "Name of the message.",
        "default": "",
        "examples": [
            "NotifyDelivered"
        ]
    },
    "msgType": {
        "$id": "#/properties/msgType",
        "type": "string",
        "title": "The msgType schema",
        "description": "Type of message.",
        "default": "",
        "examples": [
            "COMMAND",
            "DOMAIN"
        ]
    },
    "msgTopic": {
        "$id": "#/properties/msgTopic",
        "type": "string",
        "title": "The msgTopic schema",
        "description": "Topic that the message will be published & consumed from.",
        "default": "",
        "examples": [
            "NotificationCommands"
        ]
    },
    "msgPartition": {
        "$id": "#/properties/msgPartition",
        "type": "null",
        "title": "The msgPartition schema",
        "description": "Optional Kafka partition used for publishing the message to the msgTopic.",
        "default": null,
        "examples": [
            null
        ]
    },
    "msgTimestamp": {
        "$id": "#/properties/msgTimestamp",
        "type": "integer",
        "title": "The msgTimestamp schema",
        "description": "Epoch/Unix timestamp of message creation.",
        "default": 0,
        "examples": [
            1607677081837
        ]
    },
    "aggregateName": {
        "$id": "#/properties/aggregateName",
        "type": "string",
        "title": "The aggregateName schema",
        "description": "Aggregate name",
        "default": "",
        "examples": [
            "Notifications"
        ]
    },
    "aggregateId": {
        "$id": "#/properties/aggregateId",
        "type": "string",
        "title": "The aggregateId schema",
        "description": "Aggregate identifier",
        "default": "",
        "examples": [
            "861b86e6-c3da-48b3-ba17-896710287d1f"
        ]
    },
    "notifyId": {
        "$id": "#/properties/notifyId",
        "type": "string",
        "title": "The notifyId schema",
        "description": "Correlation identifier for the event that triggerd this Notification",
        "default": "",
        "examples": [
            "3920382d-f78c-4023-adf9-0d7a4a2a3a2f"
        ]
    },
    "report": {
        "$id": "#/properties/report",
        "type": "object",
        "title": "The report schema",
        "description": "Notification delivery report.",
        "default": {},
        "examples": [
            {
                "requestTimestamp": 1507677081120,
                "deliveryTimestamp": 1607677081840,
                "deliveryReqLatency": 100,
                "retryAttempts": 1,
                "response": {
                    "statusCode": "202",
                    "statusDescription": "Accepted",
                    "headers": {
                        "content-type": "application/vnd.interoperability.transfers+json;version=1.0",
                        "date": "2019-05-28T16:34:41.000Z"
                    },
                    "body": "{}"
                },
                "accepted": true,
                "errorInformation": {
                    "errorCode": "408",
                    "errorDescription": "ECONNABORTED\ntimeout of 2ms exceeded\nError: timeout of 2ms exceeded\n    at createError (/node_modules/axios/lib/core/createError.js:16:15)\n    at Timeout.handleRequestTimeout (/node_modules/axios/lib/adapters/http.js:252:16)\n    at listOnTimeout (timers.js:324:15)\n    at processTimers (timers.js:268:5)"
                }
            }
        ],
        "required": [
            "requestTimestamp",
            "accepted"
        ],
        "properties": {
            "requestTimestamp": {
                "$id": "#/properties/report/properties/requestTimestamp",
                "type": "integer",
                "title": "The requestTimestamp schema",
                "description": "Epoch/Unix timestamp of when the notification was processed.",
                "default": 0,
                "examples": [
                    1507677081120
                ]
            },
            "deliveryTimestamp": {
                "$id": "#/properties/report/properties/deliveryTimestamp",
                "type": "integer",
                "title": "The deliveryTimestamp schema",
                "description": "Epoch/Unix timestamp of when the notification was delivered.",
                "default": 0,
                "examples": [
                    1607677081840
                ]
            },
            "deliveryReqLatency": {
                "$id": "#/properties/report/properties/deliveryReqLatency",
                "type": "integer",
                "title": "The deliveryReqLatency schema",
                "description": "Request latency of the successful delivery in milliseconds.",
                "default": 0,
                "examples": [
                    100
                ]
            },
            "retryAttempts": {
                "$id": "#/properties/report/properties/retryAttempts",
                "type": "integer",
                "title": "The retryAttempts schema",
                "description": "Number of retries in the attempted notification delivery.",
                "default": 0,
                "examples": [
                    1
                ]
            },
            "response": {
                "$id": "#/properties/report/properties/response",
                "type": "object",
                "title": "The response schema",
                "description": "Transport response from the notification.",
                "default": {},
                "examples": [
                    {
                        "statusCode": "202",
                        "statusDescription": "Accepted",
                        "headers": {
                            "content-type": "application/vnd.interoperability.transfers+json;version=1.0",
                            "date": "2019-05-28T16:34:41.000Z"
                        },
                        "body": "{}"
                    }
                ],
                "required": [
                    "statusCode"
                ],
                "properties": {
                    "statusCode": {
                        "$id": "#/properties/report/properties/response/properties/statusCode",
                        "type": "string",
                        "title": "The statusCode schema",
                        "description": "Transport specific response code.",
                        "default": "",
                        "examples": [
                            "202"
                        ]
                    },
                    "statusDescription": {
                        "$id": "#/properties/report/properties/response/properties/statusDescription",
                        "type": "string",
                        "title": "The statusDescription schema",
                        "description": "Transport specific response code description if available.",
                        "default": "",
                        "examples": [
                            "Accepted"
                        ]
                    },
                    "headers": {
                      "$id": "#/properties/payload/properties/headers",
                      "type": "object",
                      "title": "The headers schema",
                      "description": "An explanation about the purpose of this instance.",
                      "default": {},
                      "examples": [
                          {
                              "content-type": "application/vnd.interoperability.transfers+json;version=1.0",
                              "date": "2019-05-28T16:34:41.000Z",
                              "fspiop-source": "payeefsp",
                              "fspiop-destination": "payerfsp"
                          }
                      ],
                      "required": [],
                      "additionalProperties": {"type": "string"}
                    },
                    "body": {
                        "$id": "#/properties/report/properties/response/properties/body",
                        "type": "string",
                        "title": "The body schema",
                        "description": "An explanation about the purpose of this instance.",
                        "default": "",
                        "examples": [
                            "{}"
                        ]
                    }
                },
                "additionalProperties": false
            },
            "accepted": {
                "$id": "#/properties/report/properties/accepted",
                "type": "boolean",
                "title": "The accepted schema",
                "description": "Boolean indicated if the notification was delivered.",
                "default": false,
                "examples": [
                    true
                ]
            },
            "errorInformation": {
                "$id": "#/properties/report/properties/errorInformation",
                "type": "object",
                "title": "The errorInformation schema",
                "description": "Notification delivery error information.",
                "default": {},
                "examples": [
                    {
                        "errorCode": "408",
                        "errorDescription": "ECONNABORTED\ntimeout of 2ms exceeded\nError: timeout of 2ms exceeded\n    at createError (/node_modules/axios/lib/core/createError.js:16:15)\n    at Timeout.handleRequestTimeout (/node_modules/axios/lib/adapters/http.js:252:16)\n    at listOnTimeout (timers.js:324:15)\n    at processTimers (timers.js:268:5)"
                    }
                ],
                "required": [
                    "errorCode",
                    "errorDescription"
                ],
                "properties": {
                    "errorCode": {
                        "$id": "#/properties/report/properties/errorInformation/properties/errorCode",
                        "type": "string",
                        "title": "The errorCode schema",
                        "description": "Internal error code.",
                        "default": "",
                        "examples": [
                            "408"
                        ]
                    },
                    "errorDescription": {
                        "$id": "#/properties/report/properties/errorInformation/properties/errorDescription",
                        "type": "string",
                        "title": "The errorDescription schema",
                        "description": "Description of the error. This could be a stack-trace.",
                        "default": "",
                        "examples": [
                            "ECONNABORTED\ntimeout of 2ms exceeded\nError: timeout of 2ms exceeded\n    at createError (/node_modules/axios/lib/core/createError.js:16:15)\n    at Timeout.handleRequestTimeout (/node_modules/axios/lib/adapters/http.js:252:16)\n    at listOnTimeout (timers.js:324:15)\n    at processTimers (timers.js:268:5)"
                        ]
                    }
                },
                "additionalProperties": false
            }
        },
        "additionalProperties": false
    },
    "traceInfo": {
      "$id": "#/properties/traceInfo",
      "type": "object",
      "title": "The traceInfo schema",
      "description": "Distributed tracing metadata for the event.",
      "default": {},
      "examples": [
          {
              "traceParent": "00-8e540e87060d56a2d2e0be5d732791e7-d96a5971b7c5cac6-21",
              "traceState": "acmevendor=eyJzcGFuSWQiOiJkOTZhNTk3MWI3YzVjYWM2IiwidGltZUFwaVByZXBhcmUiOiIxNjA3Njc3MDgxNzAwIiwidGltZUFwaUZ1bGZpbCI6IjE2MDc2NzcwODE4MTkifQ==",
              "service": "notification-evt-handler",
              "startTimestamp": 1607677081837,
              "finishTimestamp": 2007677081838
          }
      ],
      "required": [
          "traceParent",
          "traceState",
          "service",
          "startTimestamp",
          "finishTimestamp"
      ],
      "properties": {
          "traceParent": {
              "$id": "#/properties/traceInfo/properties/traceParent",
              "type": "string",
              "title": "The traceParent schema",
              "description": "Identifier for the incoming request in a tracing system. Ref: https://w3c.github.io/trace-context/#traceparent-header",
              "default": "",
              "examples": [
                  "00-8e540e87060d56a2d2e0be5d732791e7-d96a5971b7c5cac6-21"
              ]
          },
          "traceState": {
              "$id": "#/properties/traceInfo/properties/traceState",
              "type": "string",
              "title": "The traceState schema",
              "description": "Provides additional vendor-specific trace identification information across different distributed tracing systems and is a companion header for the traceparent field. Ref: https://w3c.github.io/trace-context/#tracestate-header",
              "default": "",
              "examples": [
                  "acmevendor=eyJzcGFuSWQiOiJkOTZhNTk3MWI3YzVjYWM2IiwidGltZUFwaVByZXBhcmUiOiIxNjA3Njc3MDgxNzAwIiwidGltZUFwaUZ1bGZpbCI6IjE2MDc2NzcwODE4MTkifQ=="
              ]
          },
          "service": {
              "$id": "#/properties/traceInfo/properties/service",
              "type": "string",
              "title": "The service schema",
              "description": "The service name of the event producer.",
              "default": "",
              "examples": [
                  "notification-cmd-handler"
              ]
          },
          "startTimestamp": {
              "$id": "#/properties/traceInfo/properties/startTimestamp",
              "type": "integer",
              "title": "The startTimestamp schema",
              "description": "Epoch/Unix timestamp of the trace-span's start.",
              "default": 0,
              "examples": [
                  1607677081837
              ]
          },
          "finishTimestamp": {
              "$id": "#/properties/traceInfo/properties/finishTimestamp",
              "type": "integer",
              "title": "The finishTimestamp schema",
              "description": "Epoch/Unix timestamp of the trace-span's end.",
              "default": 0,
              "examples": [
                  2007677081838
              ]
          }
      },
      "additionalProperties": false
    }
  },
  "additionalProperties": true
}

=== mojaloop/documentation/mojaloop-technical-overview/notifications/assets/examples/notifyDelivered.example-1.json
{
  "msgId": "18efb9ea-d29a-42b9-9b30-59e1e7cfe216",
  "msgKey": "861b86e6-c3da-48b3-ba17-896710287d1f",
  "msgName": "NotifyDelivered",
  "msgType": "Domain",
  "msgTopic": "NotificationCommands",
  "msgPartition": null,
  "msgTimestamp": 2007677081820,
  "aggregateName": "Notifications",
  "aggregateId": "861b86e6-c3da-48b3-ba17-896710287d1f",
  "notifyId": "3920382d-f78c-4023-adf9-0d7a4a2a3a2f",
  "report": {
    "requestTimestamp": 1507677081120,
    "deliveryTimestamp": 1607677081840,
    "deliveryReqLatency": 100,
    "retryAttempts": 1,
    "response": {
      "statusCode": "202",
      "statusDescription": "Accepted",
      "headers": {
        "content-type": "application/vnd.interoperability.transfers+json;version=1.0",
        "date": "2019-05-28T16:34:41.000Z"
      },
      "body": "{}"
    },
    "accepted": true,
    "errorInformation": {
      "errorCode": "408",
      "errorDescription": "ECONNABORTED\ntimeout of 2ms exceeded\nError: timeout of 2ms exceeded\n    at createError (/node_modules/axios/lib/core/createError.js:16:15)\n    at Timeout.handleRequestTimeout (/node_modules/axios/lib/adapters/http.js:252:16)\n    at listOnTimeout (timers.js:324:15)\n    at processTimers (timers.js:268:5)"
    }
  },
  "traceInfo": {
      "traceParent": "00-8e540e87060d56a2d2e0be5d732791e7-d96a5971b7c5cac6-21",
      "traceState": "acmevendor=eyJzcGFuSWQiOiJkOTZhNTk3MWI3YzVjYWM2IiwidGltZUFwaVByZXBhcmUiOiIxNjA3Njc3MDgxNzAwIiwidGltZUFwaUZ1bGZpbCI6IjE2MDc2NzcwODE4MTkifQ==",
      "service": "notification-Cmd-handler",
      "startTimestamp": 1607677081837,
      "finishTimestamp": 2007677081838
  }
}
